//! The workspace format, written for whoever is about to edit it — in
//! practice an agent modelling a repository for the first time.
//!
//! It exists because `spec/model-format.md` lives in *this* repository and
//! nowhere near a user's. Nothing in a fresh `blastradius init` said what
//! valid YAML looks like, so the first agent to try inferred the schema from
//! a sample file and then looped on validation errors (docs/roadmap.md,
//! first-user findings). Served by the `model_format` MCP tool and embedded
//! in the generated skill, so it is in reach before the first tool call.
//!
//! `spec/model-format.md` stays normative; this is the same rules, compressed
//! to what someone writing a model actually has to know. `EXAMPLE` is parsed
//! and validated by tests/format_ref.rs, so it cannot rot into something that
//! does not load.

/// A complete workspace, file by file: manifest, context, one system, a view,
/// and a document. Small enough to read in one go, real enough to copy.
///
/// Written to disk and validated by tests/format_ref.rs — an example that
/// does not load is worse than no example, since it is the thing an agent
/// with no other reference will imitate.
pub const EXAMPLE_FILES: &[(&str, &str)] = &[
    (
        "blastradius.yaml",
        r#"workspace:
  name: Acme
  version: 1
model:
  include: [model/*.yaml]
views:
  include: [views/*.yaml]
docs:
  include: ["*.md", "adr/*.md"]
"#,
    ),
    (
        "model/context.yaml",
        r#"people:
  shopper:
    name: Shopper
    description: Buys things.
external:
  stripe:
    name: Stripe
    description: Card payments.
"#,
    ),
    (
        "model/shop.yaml",
        r#"system: shop
name: Shop
description: Sells things.

containers:
  web:
    name: Web
    tech: React
    description: Storefront in the browser.
  api:
    name: API
    tech: Go
    components:
      catalog: { name: Catalog }
      billing: { name: Billing }
  db:
    name: Database
    tech: PostgreSQL

relations:
  - from: web
    to: api
    label: calls
    protocol: JSON/HTTPS
  - from: api.billing
    to: stripe
    label: charges cards
    protocol: REST
  - from: api
    to: db
    label: reads & writes
    protocol: SQL
  - from: shopper
    to: web
    label: browses & buys
"#,
    ),
    (
        "views/containers.yaml",
        r#"view: containers
name: Containers
scope: shop
level: L2
"#,
    ),
    (
        "adr/0001-payments.md",
        r#"---
doc: adr-0001
type: adr
status: accepted
elements: [shop.api.billing]
---

# ADR-0001: Stripe for card payments

Billing talks to Stripe directly rather than through a broker.
"#,
    ),
];

/// The example rendered as one annotated block, for the `model_format` tool
/// and the skill.
pub fn example() -> String {
    let mut s = String::new();
    for (path, body) in EXAMPLE_FILES {
        s.push_str(&format!("## {path}\n\n```\n{body}```\n\n"));
    }
    s
}

/// The format reference served by `model_format` and embedded in the skill.
pub const REFERENCE: &str = r#"# Blastradius workspace format

Plain YAML in a repository, one C4 model. Read this before writing or
repairing any of it by hand — do not infer the schema from an existing file.

Edit through the `apply_operation` and `apply_operations` MCP tools rather
than writing this YAML yourself: they splice in place (comments, key order and
formatting survive), validate before writing, refuse anything that would
invalidate the workspace, and are undoable. Hand-editing is allowed — the
files are the source of truth — but then run `validate` immediately, fix what
it reports before doing anything else, and never re-serialize or re-order a
file you did not write.

## Layout

    blastradius.yaml     manifest: name, version, and which files to include
    model/*.yaml         the model: one file per system, plus context
    model/deployment.yaml  optional: where containers run
    model/derived/       generated by `introspect` — never hand-edit
    views/*.yaml         optional: pinned layout per diagram
    *.md, adr/*.md       documents that carry frontmatter

Manifest:

    workspace:
      name: Acme
      version: 1          # integer, required
    model:  { include: [model/*.yaml] }
    views:  { include: [views/*.yaml] }
    docs:   { include: ["*.md", "adr/*.md"] }

Globs are relative to the manifest, forward slashes, `*` and `**` only. Files
matched by nothing are ignored, so a workspace can live inside a larger docs
tree.

## Ids

A YAML key *is* the element's id: lowercase `[a-z0-9-]`, up to 64 characters,
unique among siblings. **Ids are immutable** — to change what a thing is
called, set `name`, never the key; relations, views and docs address elements
by id and renaming the key breaks all of them.

Elements are addressed by dotted path: `shop.api.billing`. People and external
systems are top-level, so they are addressed by bare id: `shopper`.

## Kinds, and what may contain what

    person        top level        someone who uses a system
    external      top level        a system you do not own or model inside
    system        top level        something you own; one per model file
      container     in a system      a deployable/runnable thing: app, service, database
        component     in a container   a major part of that container

    environment   top level        top of a deployment tree
      deployment-node  in an environment or another node   a thing that runs things
        container-instance  in a node   a modelled container actually running there

Below components, code-level detail (L4) is *derived* from source by
`introspect`, never hand-modelled. Point a component at its code with:

    components:
      billing:
        name: Billing
        source: { language: csharp, root: src/Billing }

Languages: `rust`, `typescript`, `csharp`.

## Model files

`model/context.yaml` holds people and externals:

    people:
      shopper: { name: Shopper, description: Buys things. }
    external:
      stripe:  { name: Stripe }

`model/<system-id>.yaml` holds exactly one system:

    system: shop
    name: Shop
    description: Sells things.
    containers:
      web: { name: Web, tech: React }
      api:
        name: API
        tech: Go
        components:
          catalog: { name: Catalog }

`name` defaults to a titleized id; `tech` and `description` are optional.
`external: true` on a system renders it dashed. Flow style
(`catalog: { name: Catalog }`) is valid YAML and good for terse listings.

## Relations

    relations:
      - from: web
        to: api
        label: calls
        protocol: JSON/HTTPS

- **Direction is the dependency**: `from` depends on `to`. It is not a data
  flow — a request/response pair is one relation, pointing at the thing being
  called.
- `label` is what the dependency is; `protocol` is the technology, rendered in
  brackets, C4-style: `calls [JSON/HTTPS]`.
- Endpoints resolve as bare context ids, sibling ids, or dotted paths.
- `relations:` sits at system level (endpoints relative to that system), under
  a container (`from` then defaults to that container), or in a context file
  (endpoints are absolute).
- `direction: both | none` overrides the arrow; omitted means forward.

## Groups

    containers:
      web: { name: Web, group: Storefront }
      api: { name: API, group: Storefront }

Presentation only: a boundary drawn round siblings sharing a label. No
nesting level, no id change, no new parent. Rendered only where a view says
`show-groups: true`.

## Deployment

`model/deployment.yaml`, every environment in one file:

    environments:
      prod:
        name: Production
        nodes:
          eu-west:
            name: AWS eu-west-1
            nodes:
              app:
                name: ECS service
                tech: Fargate
                instances:
                  api: { container: shop.api }
        relations:
          - from: eu-west
            to: office.vpn
            label: peers with

`instances:` entries reference a `container` element; a dangling reference is
an error, which is the point of modelling deployment here rather than in prose.

## Views

Optional — every level renders without any view file.

    view: containers
    name: Containers
    scope: shop        # the element being looked inside
    level: L2          # L1 | L2 | L3 | LD
    layout:            # pinned positions, grid units; anything absent is auto-placed
      web: [4, 2]
    show-groups: false
    include-context: true

`scope` is required except on an `LD` overview of every environment.

## Documents

A markdown file matched by `docs.include` joins the model if it starts with
frontmatter:

    ---
    doc: adr-0007        # unique workspace-wide, same slug rules
    type: adr            # prd | adr | spec | roadmap | note
    status: accepted     # adr: proposed|accepted|superseded|rejected
                         # prd|spec|roadmap: draft|current|superseded
    elements: [shop.api.billing]
    supersedes: adr-0004 # optional, adr only
    ---

A matched file without frontmatter is ignored, not an error.

## What makes a workspace invalid

Errors: duplicate id among siblings; a dangling reference from a relation,
a view layout, or a doc's `elements:`; unknown schema version; malformed YAML.
Warnings: unknown doc `type`; an empty system; a relation duplicated verbatim.
Everything is reported with file and line — run `validate` and read it.
"#;

/// Modelling guidance, as distinct from format. Embedded in every agent's
/// primer and returned by `model_format`: an agent that knows the schema
/// perfectly can still produce a model nobody will keep (owner request,
/// docs/roadmap.md).
pub const PRACTICE: &str = r#"# Modelling rules

Getting the format right is not the same as modelling well.

- **Stop at components.** Below them is derived from source by `introspect`.
  Hand-modelling classes and functions is the classic way to build a model
  nobody maintains.
- **A relation is a dependency, not a data flow.** Blastradius's own model got
  this wrong — a relation labelled "parse results" pointed one way while the
  code dependency ran the other, and drift detection caught it. Ask "which one
  would break if the other changed?" and point from the answer.
- **Model what a reader needs to reason about**, not everything that exists. A
  container diagram with forty boxes has failed at its job.
- **Name things after what they are**, and put technology in `tech:` — a
  container called "Redis Cache" should be "Cache" with `tech: Redis`.
- **One system per file**, named for the system id.
- **Attach documents to the elements they govern.** A doc naming an element
  that no longer exists is a model error, and validation says so.
- **Run `validate` before claiming to be done**, and `blast_radius` on
  anything you are about to change or delete.
"#;

/// Everything the `model_format` tool returns: the rules, then a workspace
/// that actually loads.
pub fn full_reference() -> String {
    format!("{REFERENCE}\n{PRACTICE}\n# A complete example workspace\n\n{}", example())
}
